on:
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: "20 */4 * * *"
    
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    permissions:
      actions: write
      
    steps:
      - uses: actions/checkout@main
      
      - name: Remove older workflow runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $runs = gh run list -L 400 --repo $env:GITHUB_REPOSITORY --json databaseId | ConvertFrom-Json
          
          if ($runs.Count -gt 10) {
            $runs | Select-Object -Skip 10 | ForEach-Object {
              gh api "repos/$env:GITHUB_REPOSITORY/actions/runs/$($_.databaseId)" -X DELETE
            }
          }
      
      - name: Check for updates
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: 1

